### ISSUE TITLE
When adding +k8s:validateFalse to a struct pointer, the current generated code can panic w/ a nil pointer dereference

### ISSUE THREAD

**Issue by aaron-prindle** [jpbetz/kubernetes#75]
### What happened?

Currently in the code if you have a [doc.go](http://doc.go/) like the below:

```go
// T2 has string, slice, pointer and map fields to test inner field validations across types
type T2 struct {
	// +k8s:validateFalse="field T2.StringFieldWithValidation"
	StringFieldWithValidation string `json:"stringFieldWithValidation"`
}

// T1 demonstrates validations for inner fields of structs.
// +k8s:validateFalse="type T1"
type T1 struct {
	TypeMeta int `json:"typeMeta"`
	PT2      *T2 `json:"pt2"`
}
```

The generated code for T2 looks like:
```go
func Validate_T2(opCtx operation.Context, obj, oldObj *T2, fldPath *field.Path) (errs field.ErrorList) {
	// field T2.StringFieldWithValidation
	errs = append(errs,
		func(obj, oldObj *string, fldPath *field.Path) (errs field.ErrorList) {
			errs = append(errs, validate.FixedResult(opCtx, fldPath, obj, oldObj, false, "field T2.StringFieldWithValidation")...)
			return
                        // FIXME: vvvv &obj.StringFieldWithValidation panics
			}(&obj.StringFieldWithValidation, safe.Field(oldObj, func(oldObj *T2) *string { return &oldObj.StringFieldWithValidation }), fldPath.Child("stringFieldWithValidation"))...)

	return errs
}
```

With this generated code, there is a &obj.StringFieldValidation passed into the func(obj, oldObj *string, fldPath *field.Path) even though &obj can be nil -> nil pointer dereference -> panic

Is this intended in the current code?  Is this WAI, should this validation currently not have this issue (eg: the generated code handles this) or would the idea be that there is another validator tag (IsNil, etc.) that is added to nil struct pointers that handles this?

For example this test:

```go
func TestStructPointerWithFieldValidation(t *testing.T) {
	cases := []struct {
		name          string
		obj           *T1
		expectedPaths []string
		expectErrors  bool
	}{
		{
			name: "T1.PT2.StringFieldWithValidation validation when PT2 is nli",
			obj: &T1{
				PT2: nil,
			},
			expectedPaths: []string{""},
			expectErrors:  true,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			opCtx := operation.Context{}
			errs := Validate_T1(opCtx, tc.obj, tc.obj, nil)
			if tc.expectErrors && len(errs) == 0 {
				t.Error("expected validation errors but got none")
			}
			if !tc.expectErrors && len(errs) > 0 {
				t.Errorf("unexpected validation errors: %v", errs)
			}
			expectedPathCount := 0
			actualPaths := []string{}
			for _, err := range errs {
				actualPaths = append(actualPaths, err.Field)
				for _, expectedPath := range tc.expectedPaths {
					if err.Field == expectedPath {
						expectedPathCount++
					}
				}

			}
			if tc.expectErrors && expectedPathCount != len(tc.expectedPaths) {
				t.Errorf("expected error paths %q in %q", tc.expectedPaths, actualPaths)
			}
		})
	}
}
```
panics as it has `PT2: nil`
```console
Running tool: /usr/lib/google-golang/bin/go test -timeout 30s -run ^TestInnerValidationWithValidateFalse$ k8s.io/code-generator/cmd/validation-gen/output_tests/repro

--- FAIL: TestInnerValidationWithValidateFalse (0.00s)
    --- FAIL: TestInnerValidationWithValidateFalse/T1.PT2.StringFieldWithValidation_validation_when_PT2_is_nli (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78f85c]

goroutine 21 [running]:
testing.tRunner.func1.2({0x7bce20, 0xa406c0})
	/usr/lib/google-golang/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/usr/lib/google-golang/src/testing/testing.go:1635 +0x35e
panic({0x7bce20?, 0xa406c0?})
	/usr/lib/google-golang/src/runtime/panic.go:785 +0x132
k8s.io/code-generator/cmd/validation-gen/output_tests/repro.Validate_T2({0x0?, 0x0?}, 0x0, 0x0?, 0xc0001a4ae0)
	/usr/local/google/home/aprindle/kubernetes/staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/repro/zz_generated.validations.go:70 +0xbc
k8s.io/code-generator/cmd/validation-gen/output_tests/repro.Validate_T1.func1(...)
	/usr/local/google/home/aprindle/kubernetes/staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/repro/zz_generated.validations.go:57
k8s.io/code-generator/cmd/validation-gen/output_tests/repro.Validate_T1({0x6a79ed?, 0x0?}, 0xc00019e430, 0xc00019e430, 0x0)
	/usr/local/google/home/aprindle/kubernetes/staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/repro/zz_generated.validations.go:59 +0x187
k8s.io/code-generator/cmd/validation-gen/output_tests/repro.TestInnerValidationWithValidateFalse.func1(0xc0001d6680)
	/usr/local/google/home/aprindle/kubernetes/staging/src/k8s.io/code-generator/cmd/validation-gen/output_tests/repro/doc_test.go:45 +0x3c
testing.tRunner(0xc0001d6680, 0xc0001b4a40)
	/usr/lib/google-golang/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 20
	/usr/lib/google-golang/src/testing/testing.go:1743 +0x390
FAIL	k8s.io/code-generator/cmd/validation-gen/output_tests/repro	0.018s
FAIL

```

### What did you expect to happen?

I expect the generated code not to panic for this case (but this might be WAI)

### How can we reproduce it (as minimally and precisely as possible)?

See above for repro

**Comment by aaron-prindle** [comment]
Talked offline, forbidden has the same issue the test currently does not have a validation on a struct pointer field

```go
type T1 struct {
	TypeMeta int

	// +k8s:forbidden
	S string `json:"s"`
	// +k8s:forbidden
	PS *string `json:"ps"`

	// non-pointer struct fields cannot be forbiden

	// +k8s:forbidden
	PT2 *T2 `json:"pt2"`
}

type T2 struct {
	S string `json:"s"` // <--- IF THIS FIELD HAD A VALIDATION ON IT, THE SAME ERROR WOULD HAPPEN
}

```

**Comment by thockin** [comment]
This is the "if it is not marked optional, it's implicitly required" problem.

For the purposes of testing you need to always provide a value.  We don't want to add the test for nil because it can silently hide bugs - it's not supposed to be nil.

**Comment by aaron-prindle** [comment]
Closing, as per Tim's comment this is not a bug and is WAI
